services:
  db:
    image: postgres:16-alpine
    container_name: censorly_db
    environment:
      POSTGRES_USER: censorly
      POSTGRES_PASSWORD: censorly
      POSTGRES_DB: censorly
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: censorly_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: censorly_minio
    command: server /data --console-address ":9101"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9100:9000" # S3 API
      - "9101:9101" # Console
    volumes:
      - miniodata:/data
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    container_name: censorly_api
    env_file:
      - ../.env.prod
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "8100:8000"
    restart: unless-stopped
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000

  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
      # (isteğe bağlı) Vite build'ine API adresini arg olarak geçirmek istersen:
      # args:
      #   - VITE_API_URL=http://194.146.50.83:8100
    container_name: censorly_web
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://194.146.50.83:8100 # frontend’in API’ye vuracağı adres
    ports:
      - "8101:3000"
    restart: unless-stopped
    # build edip çıkmak yerine gerçekten servis et:
    command:
      ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "3000"]

  worker:
    build:
      context: ..
      dockerfile: docker/worker.Dockerfile
    container_name: censorly_worker
    env_file:
      - ../.env.prod
    depends_on:
      - db
      - redis
      - minio
    working_dir: /app/apps/worker # doğru dizin
    command: ["python", "main.py"] # doğru entry
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  miniodata:
