version: "3.9"
services:
  api:
    build:
      context: ../
      dockerfile: docker/api.Dockerfile
    env_file:
      - ../configs/api.env.sample
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
  worker:
    build:
      context: ../
      dockerfile: docker/worker.Dockerfile
    env_file:
      - ../configs/worker.env.sample
    depends_on:
      - api
  web:
    build:
      context: ../
      dockerfile: docker/web.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../:/app
  # redis ve db servisleri demo için yorumda bırakıldı
  # redis:
  #   image: redis:7-alpine
  #   ports: ["6379:6379"]
  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_PASSWORD: password
  #   ports: ["5432:5432"]
